DROP TABLE IF EXISTS tea.data
  ,tea.prof_map
  ,tea.meta_color
  ,tea.meta_brdwn
  ,tea.meta_brdwn_code
  ,tea.meta_color_priority
  ,tea.meta_value_code
  ,tea.routes_used;

--data
CREATE TABLE tea.data (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,year SMALLINT
  ,level_h SMALLINT
  ,code_h TEXT
  ,level_w INTEGER
  ,code_w TEXT
  ,brdwn TEXT
  ,brdwn_code TEXT
  ,value_code TEXT
  ,value_ind NUMERIC
  );

--prof_map

CREATE TABLE tea.prof_map (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,code VARCHAR(7)
  ,prof_code VARCHAR(3)
  );

INSERT INTO tea.prof_map (
  code
  ,prof_code
  )
VALUES (
  '1'
  ,'G01'
  )
  ,(
  '21'
  ,'G06'
  )
  ,(
  '221'
  ,'G02'
  )
  ,(
  '222'
  ,'G02'
  )
  ,(
  '223'
  ,'G02'
  )
  ,(
  '224'
  ,'G02'
  )
  ,(
  '225'
  ,'G02'
  )
  ,(
  '232'
  ,'G03'
  )
  ,(
  '233'
  ,'G03'
  )
  ,(
  '234'
  ,'G03'
  )
  ,(
  '235'
  ,'G03'
  )
  ,(
  '2411'
  ,'G10'
  )
  ,(
  '2412'
  ,'G10'
  )
  ,(
  '2413'
  ,'G10'
  )
  ,(
  '2422'
  ,'G04'
  )
  ,(
  '25'
  ,'G05'
  )
  ,(
  '261'
  ,'G09'
  )
  ,(
  '31'
  ,'G06'
  )
  ,(
  '321'
  ,'G02'
  )
  ,(
  '322'
  ,'G02'
  )
  ,(
  '323'
  ,'G02'
  )
  ,(
  '325'
  ,'G02'
  )
  ,(
  '334'
  ,'G07'
  )
  ,(
  '3351'
  ,'G08'
  )
  ,(
  '3359'
  ,'G04'
  )
  ,(
  '3411'
  ,'G09'
  )
  ,(
  '35'
  ,'G05'
  )
  ,(
  '431'
  ,'G10'
  )
  ,(
  '4321'
  ,'G11'
  )
  ,(
  '4323'
  ,'G11'
  )
  ,(
  '512'
  ,'G12'
  )
  ,(
  '513'
  ,'G12'
  )
  ,(
  '531'
  ,'G03'
  )
  ,(
  '54'
  ,'G13'
  )
  ,(
  '71'
  ,'G14'
  )
  ,(
  '72'
  ,'G17'
  )
  ,(
  '73'
  ,'G17'
  )
  ,(
  '74'
  ,'G17'
  )
  ,(
  '75'
  ,'G17'
  )
  ,(
  '81'
  ,'G17'
  )
  ,(
  '82'
  ,'G17'
  )
  ,(
  '83'
  ,'G15'
  )
  ,(
  '9112'
  ,'G16'
  )
  ,(
  '912'
  ,'G18'
  )
  ,(
  '92'
  ,'G18'
  )
  ,(
  '9311'
  ,'G18'
  )
  ,(
  '9312'
  ,'G14'
  )
  ,(
  '9313'
  ,'G14'
  )
  ,(
  '932'
  ,'G18'
  )
  ,(
  '933'
  ,'G18'
  )
  ,(
  '9411'
  ,'G12'
  )
  ,(
  '941201'
  ,'G12'
  )
  ,(
  '941202'
  ,'G12'
  )
  ,(
  '941203'
  ,'G18'
  )
  ,(
  '941204'
  ,'G18'
  )
  ,(
  '95'
  ,'G18'
  )
  ,(
  '9611'
  ,'G18'
  )
  ,(
  '9612'
  ,'G18'
  )
  ,(
  '9613'
  ,'G16'
  )
  ,(
  '962'
  ,'G18'
  );

--meta_color

CREATE TABLE tea.meta_color (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,classes_max SMALLINT
  ,class SMALLINT
  ,color VARCHAR(7)
  );

INSERT INTO tea.meta_color (
  classes_max
  ,class
  ,color
  )
VALUES (
  5
  ,1
  ,'#A8DDEE'
  )
  ,(
  5
  ,2
  ,'#7FB4C4'
  )
  ,(
  5
  ,3
  ,'#578C9B'
  )
  ,(
  5
  ,4
  ,'#306674'
  )
  ,(
  5
  ,5
  ,'#004250'
  )
  ,(
  4
  ,1
  ,'#A8DDEE'
  )
  ,(
  4
  ,2
  ,'#72A6B6'
  )
  ,(
  4
  ,3
  ,'#3E7281'
  )
  ,(
  4
  ,4
  ,'#004250'
  )
  ,(
  3
  ,1
  ,'#A8DDEE'
  )
  ,(
  3
  ,2
  ,'#578C9B'
  )
  ,(
  3
  ,3
  ,'#004250'
  )
  ,(
  2
  ,1
  ,'#7FB4C4'
  )
  ,(
  2
  ,2
  ,'#306674'
  )
  ,(
  1
  ,1
  ,'#578C9B'
  );

--meta_brdwn_code
CREATE TABLE tea.meta_brdwn_code (
  brdwn TEXT NOT NULL
  ,brdwn_code TEXT NOT NULL
  ,name_lv TEXT
  ,name_lv_acc TEXT
  ,name_lv_dat TEXT
  ,name_lv_gen TEXT
  ,name_lv_loc TEXT
  ,name_en TEXT
  ,CONSTRAINT meta_brdwn_code_pkey PRIMARY KEY (
    brdwn
    ,brdwn_code
    )
  );

--meta_color_priority
CREATE TABLE tea.meta_color_priority (
  brdwn TEXT NOT NULL
  ,brdwn_code TEXT NOT NULL
  ,color_id SMALLINT
  ,CONSTRAINT meta_color_priority_pkey PRIMARY KEY (
    brdwn
    ,brdwn_code
    )
  );

--meta_brdwn
CREATE TABLE tea.meta_brdwn (
  brdwn TEXT PRIMARY KEY
  ,name_lv TEXT
  ,name_lv_acc TEXT
  ,name_lv_dat TEXT
  ,name_lv_gen TEXT
  ,name_lv_loc TEXT
  ,name_en TEXT
  );

--meta_value_code
CREATE TABLE tea.meta_value_code (
  value_code TEXT PRIMARY KEY
  ,name_lv TEXT
  ,name_lv_acc TEXT
  ,name_lv_dat TEXT
  ,name_lv_gen TEXT
  ,name_lv_loc TEXT
  ,name_en TEXT
  );

--routes_used
CREATE TABLE tea.routes_used (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,url TEXT NOT NULL
  ,date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,CONSTRAINT routes_used_unique UNIQUE (url) INCLUDE(id)
  );

--Ownership and permissions.

ALTER TABLE tea.data OWNER TO editor;

ALTER TABLE tea.prof_map OWNER TO editor;

ALTER TABLE tea.meta_color OWNER TO editor;

ALTER TABLE tea.meta_color_priority OWNER TO editor;

ALTER TABLE tea.meta_brdwn_code OWNER TO editor;

ALTER TABLE tea.meta_brdwn OWNER TO editor;

ALTER TABLE tea.meta_value_code OWNER TO editor;

ALTER TABLE tea.routes_used OWNER TO editor;

GRANT SELECT
  ON TABLE tea.data
    ,tea.meta_color
    ,tea.meta_color_priority
    ,tea.meta_brdwn_code
    ,tea.meta_brdwn
    ,tea.meta_value_code
    ,tea.routes_used
  TO vdvv_web;

GRANT INSERT
  ,UPDATE
  ON TABLE tea.routes_used
  TO vdvv_web;

GRANT SELECT
  ON TABLE tea.data
    ,tea.meta_brdwn_code
    ,tea.meta_brdwn
    ,tea.meta_value_code
  TO editor_texts;