DROP SCHEMA IF EXISTS tea CASCADE;

CREATE SCHEMA IF NOT EXISTS tea;

ALTER SCHEMA tea OWNER TO editor;

GRANT ALL ON SCHEMA tea TO tea_dev;

GRANT USAGE ON SCHEMA tea TO basic_user, vdvv_web, editor_texts, admin_texts;

ALTER DEFAULT PRIVILEGES IN SCHEMA tea
GRANT SELECT ON TABLES TO basic_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA tea
GRANT SELECT ON SEQUENCES TO basic_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA tea
GRANT EXECUTE ON FUNCTIONS TO tea_dev, basic_user, vdvv_web, editor_texts, admin_texts;

ALTER DEFAULT PRIVILEGES
FOR ROLE tea_dev
IN SCHEMA tea
GRANT ALL ON TABLES TO editor;

ALTER DEFAULT PRIVILEGES
FOR ROLE tea_dev
IN SCHEMA tea
GRANT ALL ON SEQUENCES TO editor;

ALTER DEFAULT PRIVILEGES
FOR ROLE tea_dev
IN SCHEMA tea
GRANT EXECUTE ON FUNCTIONS TO editor;

ALTER DEFAULT PRIVILEGES
FOR ROLE tea_dev
IN SCHEMA tea
GRANT SELECT ON TABLES TO basic_user;

ALTER DEFAULT PRIVILEGES
FOR ROLE tea_dev
IN SCHEMA tea
GRANT SELECT ON SEQUENCES TO basic_user;

ALTER DEFAULT PRIVILEGES
FOR ROLE tea_dev
IN SCHEMA tea
GRANT EXECUTE ON FUNCTIONS TO editor, basic_user, vdvv_web, editor_texts, admin_texts;