DROP TABLE IF EXISTS tea.texts_pop;

CREATE TABLE tea.texts_pop (
  p_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,home_work TEXT
  ,indicator_type TEXT
  ,selected_territ TEXT
  ,indicator_selected TEXT
  ,breakdown_selected TEXT
  ,request_type TEXT
  ,text_display_lv TEXT
  ,text_display_en TEXT
  ,sql_string_from_join TEXT
  ,sql_string_where TEXT
  );

ALTER TABLE tea.texts_pop OWNER TO editor;

GRANT SELECT
  ON TABLE tea.texts_pop
  TO vdvv_web
    ,editor_texts
    ,admin_texts;

GRANT UPDATE
  ON TABLE tea.texts_pop
  TO editor_texts
    ,admin_texts;

GRANT DELETE
  ,INSERT
  ON TABLE tea.texts_pop
  TO admin_texts;

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'all'
  ,'none'
  ,'none'
  ,'over'
  ,
  't_h.name_lv_loc,
'' dzīvo <b>'',
get_pretty_number(''lv'', pop_wa.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', pop_wa.value_ind) LIKE ''% %''
    THEN ''iedzīvotāju''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', pop_wa.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', pop_wa.value_ind), 2) NOT LIKE ''11''
    THEN ''iedzīvotājs''
  ELSE ''iedzīvotāji''
  END,
'' darbspējas vecumā (15–64 gadi), no kuriem '',
CASE 
  WHEN RIGHT(get_pretty_number_num_part(''lv'', rel.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', rel.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbināts''
  ELSE ''nodarbināti''
  END,
'' ir <b>'',
get_pretty_number(''lv'', rel.value_ind),
''</b>'',
CASE 
  WHEN RIGHT(get_pretty_number(''lv'', rel.value_ind), 1) LIKE ''.''
    THEN NULL
  ELSE ''.''
  END,
''</br>Nodarbinātības līmenis ir <b>'',
get_pretty_number(''lv'', 100 * main.value_ind::DECIMAL / pop_wa.value_ind),
''</b>%.'''
  ,'''There are <b>'',
get_pretty_number(''en'', pop_wa.value_ind),
''</b> resident population of working age (15–64 years) living in '',
t_h.name_en,
'', of whom <b>'',
get_pretty_number(''en'', rel.value_ind),
''</b> are employed.</br>Employment rate is <b>'',
get_pretty_number(''en'', 100 * main.value_ind::DECIMAL / pop_wa.value_ind),
''</b>%.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'all'
  ,'none'
  ,'none'
  ,'over'
  ,
  't_w.name_lv_loc,
'' atrodas <b>'',
get_pretty_number(''lv'', main.value_ind),
'' </b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvieta''
  ELSE LOWER(m_v_c.name_lv)
  END,
'' un dzīvo <b>'',
get_pretty_number(''lv'', pop_wa.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', pop_wa.value_ind) LIKE ''% %''
    THEN ''iedzīvotāju''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', pop_wa.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', pop_wa.value_ind), 2) NOT LIKE ''11''
    THEN ''iedzīvotājs''
  ELSE ''iedzīvotāji''
  END,
'' darbspējas vecumā (15–64 gadi).<br>'',
m_v_c.name_lv_gen,
'' skaits uz 100 darbspējas vecuma iedzīvotājiem ir <b>'',
REPLACE(ROUND(rel_w.value_ind::DECIMAL / pop_wa.value_ind * 100, 1)::TEXT, ''.'', '',''),
''</b>.'''
  ,'''There are <b>'',
get_pretty_number(''en'', main.value_ind),
'' </b> '',
LOWER(m_v_c.name_en),
'' and <b>'',
get_pretty_number(''en'', pop_wa.value_ind),
''</b> resident population of working age (15–64 years) living in '',
t_w.name_en,
''.<br>The number of '',
LOWER(m_v_c.name_en),
'' per 100 resident population of working age is <b>'',
ROUND(rel_w.value_ind::DECIMAL / pop_wa.value_ind * 100, 1),
''</b>.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'all'
  ,'selected'
  ,'none'
  ,'over'
  ,'t_h.name_lv_gen,
'' iedzīvotāji visbiežāk nodarbināti '',
CASE 
    WHEN m_b.name_lv LIKE ''Sektors''
      THEN LOWER(m_b_c.name_lv_loc)
    ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
    END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no visiem '',
t_h.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b>).'''
  ,'''Resident population of '',
t_h.name_en,
'' are most often employed in '',
CASE 
    WHEN m_b.name_en LIKE ''Sector''
      THEN LOWER(m_b_c.name_en)
    ELSE m_b_c.name_en
    END,
'' – <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
'' (<b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'all'
  ,'selected'
  ,'none'
  ,'over'
  ,'t_w.name_lv_loc,
'' visvairāk '',
LOWER(m_v_c.name_lv_gen),
'' ir '',
CASE 
    WHEN m_b.name_lv LIKE ''Sektors''
      THEN LOWER(m_b_c.name_lv_loc)
    ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
    END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no visām '',
t_w.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b>).'''
  ,'''The largest number of '',
LOWER(m_v_c.name_en),
'' in '',
t_w.name_en,
'' is in '',
CASE 
    WHEN m_b.name_en LIKE ''Sector''
      THEN LOWER(m_b_c.name_en)
    ELSE m_b_c.name_en
    END,
'' – <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' in '',
t_w.name_en,
'' (<b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'all'
  ,'selected'
  ,'selected'
  ,'over'
  ,'t_h.name_lv_loc,
'' '',
CASE 
    WHEN m_b.name_lv LIKE ''Sektors''
      THEN LOWER(m_b_c.name_lv_loc)
    ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
    END,
'' strādā <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN ''nodarbināto''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātais''
  ELSE ''nodarbinātie''
  END,
'' jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no visiem '',
t_h.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b>).'''
  ,'''In '',
t_h.name_en,
'', <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> employees or <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
'' (<b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>) are employed in '',
CASE 
    WHEN m_b.name_en LIKE ''Sector''
      THEN LOWER(m_b_c.name_en)
    ELSE m_b_c.name_en
    END,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'all'
  ,'selected'
  ,'selected'
  ,'over'
  ,'t_w.name_lv_loc,
'' '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvieta''
  ELSE LOWER(m_v_c.name_lv)
  END,
'' jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no visām '',
t_w.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b>).'''
  ,'''In '',
t_w.name_en,
'', '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' has <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' or <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' that are available in '',
t_w.name_en,
'' (<b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'over'
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tt_rel.value_ind),
''</b>% no visiem '',
t_h.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' strādā '',
t_w.name_lv_loc,
''.'''
  ,'''<b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tt_rel.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
'' are employed in '',
t_w.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'over'
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / t_ter_sel.value_ind),
''</b>% no visām '',
t_h.name_lv_gen,
'' iedzīvotāju '',
LOWER(m_v_c.name_lv_dat),
'' atrodas '',
t_w.name_lv_loc,
''.'''
  ,'''<b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or <b>'',
get_pretty_number(''en'', 100 * main.value_ind / t_ter_sel.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of the resident population of '',
t_h.name_en,
'' are located in '',
t_w.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'over'
  ,
  't_h.name_lv_gen,
'' iedzīvotāji '',
t_w.name_lv_loc,
'' visbiežāk strādā '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN ''nodarbināto''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātais''
  ELSE ''nodarbinātie''
  END,
''.<br> Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> '',
t_h.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', ter.value_ind) LIKE ''% %''
    THEN ''iedzīvotāju''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 2) NOT LIKE ''11''
    THEN ''iedzīvotāja''
  ELSE ''iedzīvotājiem''
  END,
'', kas strādā '',
t_w.name_lv_loc,
''.<br><br>'',
t_w.name_lv_loc,
'' strādā <b>'',
get_pretty_number(''lv'', 100 * ter.value_ind / ter_sel.value_ind),
''</b>% no visiem '',
t_h.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
''.'''
  ,'''Resident population of '',
t_h.name_en,
'' who are employed in '',
t_w.name_en,
'' most often work in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> employees.<br> This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b> resident population of '',
t_h.name_en,
'' who are employed in '',
t_w.name_en,
''.<br><br><b>'',
get_pretty_number(''en'', 100 * ter.value_ind / ter_sel.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
'' are employed in '',
t_w.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'over'
  ,
  't_h.name_lv_gen,
'' iedzīvotāji '',
t_w.name_lv_loc,
'' visbiežāk nodarbināti '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
''.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no '',
t_w.name_lv_gen,
'' <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', ter.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietas''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
'', kurās nodarbināti '',
t_h.name_lv_gen,
'' iedzīvotāji.<br><br>'',
t_w.name_lv_loc,
'' atrodas <b>'',
get_pretty_number(''lv'', 100 * ter.value_ind / ter_sel.value_ind),
''</b>% no visām '',
t_h.name_lv_gen,
'' iedzīvotāju '',
LOWER(m_v_c.name_lv_dat),
''.'''
  ,'''Resident population of '',
t_h.name_en,
'' in '',
t_w.name_en,
'' are most often employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – in <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
''.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' in '',
t_w.name_en,
'', which employ resident population of '',
t_h.name_en,
''.<br><br>There are <b>'',
get_pretty_number(''en'', 100 * ter.value_ind / ter_sel.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
'' population residents in '',
t_w.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'over'
  ,
  '''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
t_h.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN ''iedzīvotāju''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''iedzīvotājs''
  ELSE ''iedzīvotāji''
  END,
'', kas strādā '',
t_w.name_lv_loc,
'', nodarbināti '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
''.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> '',
t_h.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', ter.value_ind) LIKE ''% %''
    THEN ''iedzīvotāju''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 2) NOT LIKE ''11''
    THEN ''iedzīvotāja''
  ELSE ''iedzīvotājiem''
  END,
'', kas strādā '',
t_w.name_lv_loc,
''.'''
  ,'''<b>'',
get_pretty_number(''en'', main.value_ind),
''</b> resident population of '',
t_h.name_en,
'' who are employed in '',
t_w.name_en,
'' work in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
''.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b> '',
t_h.name_en,
'' resident population who are employed in '',
t_w.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'over'
  ,
  't_h.name_lv_gen,
'' iedzīvotāji, kas strādā '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'', nodarbināti <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
t_w.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
''.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no '',
t_w.name_lv_gen,
'' <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', ter.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietas''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
'', kurās nodarbināti '',
t_h.name_lv_gen,
'' iedzīvotāji.'''
  ,'''Resident population of '',
t_h.name_en,
'' who are employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' take up <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of '',
t_w.name_en,
''.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of '',
t_w.name_en,
'', which employ the resident population of '',
t_h.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'all'
  ,'none'
  ,'none'
  ,'over'
  ,'t_h.name_lv_gen,
'' nodarbināto iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the employed population of '',
t_h.name_en,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per employee.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'all'
  ,'none'
  ,'none'
  ,'over'
  ,'t_w.name_lv_gen,
'' darbvietās gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year in the jobs of '',
t_w.name_en,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per job.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'all'
  ,'selected'
  ,'none'
  ,'over'
  ,'t_h.name_lv_gen,
'' nodarbināto iedzīvotāju vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iedzīvotāju radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The highest '',
LOWER(m_v_c.name_en),
'', generated by the employed population of '',
t_h.name_en,
'' over the year, is in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per employee.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by the resident population of '',
t_h.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'all'
  ,'selected'
  ,'none'
  ,'over'
  ,'t_w.name_lv_gen,
'' darbvietās vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_w.name_lv_gen,
'' darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The highest '',
LOWER(m_v_c.name_en),
'', generated over the year in the jobs of '',
t_w.name_en,
'', is in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per job.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated in jobs of '',
t_w.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'all'
  ,'selected'
  ,'selected'
  ,'over'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'', gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iedzīvotāju radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by employed population of '',
t_h.name_en,
'' who work in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per employee.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by resident population of '',
t_h.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'all'
  ,'selected'
  ,'selected'
  ,'over'
  ,'t_w.name_lv_gen,
'' darbvietās '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_w.name_lv_gen,
'' darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year in the jobs of '',
t_w.name_en,
'' in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per job.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated in jobs of '',
t_w.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'over'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā '',
t_w.name_lv_loc,
'', gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'' who are employed in '',
t_w.name_en,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per employee.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'over'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā '',
t_w.name_lv_loc,
'', gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'' who are employed in '',
t_w.name_en,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per job.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'over'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā '',
t_w.name_lv_loc,
'', vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iedzīvotāju, kas strādā '',
t_w.name_lv_loc,
'', radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The highest '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'' who are employed in '',
t_w.name_en,
'', is in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per employee.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by resident population of '',
t_h.name_en,
'', employed in '',
t_w.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'over'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā '',
t_w.name_lv_loc,
'', vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iedzīvotāju '',
t_w.name_lv_gen,
'' darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The highest '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'' who are employed in '',
t_w.name_en,
'', is in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per job.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by resident population of '',
t_h.name_en,
'', taking up jobs in '',
t_w.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'over'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā '',
t_w.name_lv_loc,
'', '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iedzīvotāju, kas strādā '',
t_w.name_lv_loc,
'', radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'' who are employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' in '',
t_w.name_en,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per employee.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by resident population of '',
t_h.name_en,
'' who are employed in '',
t_w.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'over'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā '',
t_w.name_lv_loc,
'', '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iedzīvotāju '',
t_w.name_lv_gen,
'' darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'' who are employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' in '',
t_w.name_en,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per job.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by resident population of '',
t_h.name_en,
'' employed in jobs of '',
t_w.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'panel'
  ,'''kā dzīves vieta<br>Iedzīvotāji darbspējas vecumā (15–64 gadi): <b>'',
get_pretty_number(''lv'', pop_wa.value_ind),
''</b><br>No tiem nodarbināti: <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>Nodarbinātības līmenis: <b>'',
REPLACE(ROUND(main.value_ind / pop_wa.value_ind::NUMERIC * 100, 1)::TEXT, ''.'', '',''),
''</b>%'''
  ,'''as place of residence<br>Population of working age (aged 15–64): <b>'',
get_pretty_number(''en'', pop_wa.value_ind),
''</b><br>Of these employed: <b>'',
get_pretty_number(''en'', main.value_ind),
''</b><br>Employment rate: <b>'',
ROUND(main.value_ind / pop_wa.value_ind::NUMERIC * 100, 1),
''</b>%'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'panel'
  ,'''kā darba vieta<br>Iedzīvotāji darbspējas vecumā (15–64 gadi): <b>'',
get_pretty_number(''lv'', pop_wa.value_ind),
''</b><br>'',
m_v_c.name_lv_gen,
'' skaits: <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>'',
m_v_c.name_lv_gen,
'' skaits uz 100 darbspējas vecuma iedzīvotājiem: <b>'',
REPLACE(ROUND(main.value_ind / pop_wa.value_ind * 100, 1)::TEXT, ''.'', '',''),
''</b>'''
  ,'''as place of work<br>Population of working age (aged 15–64): <b>'',
get_pretty_number(''en'', pop_wa.value_ind),
''</b><br>Number of '',
LOWER(m_v_c.name_en),
'': <b>'',
get_pretty_number(''en'', main.value_ind),
''</b><br>Number of '',
LOWER(m_v_c.name_en),
'' per 100 inhabitants of working age: <b>'',
ROUND(main.value_ind / pop_wa.value_ind * 100, 1),
''</b>'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'panel'
  ,'''kā dzīves vieta<br>'',
m_v_c.name_lv_gen,
'' skaits: <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b><br>Visvairāk '',
CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN LOWER(m_b_c.name_lv_gen)
    ELSE LOWER(m_v_c.name_lv_gen) || '' '' || LOWER(m_b_c.name_lv_loc)
    END,
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>'',
m_b.name_lv_gen,
'' īpatsvars: <b>'',
REPLACE(ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1)::TEXT, ''.'', '',''),
''</b>%<br><br>Viens iedzīvotājs, kas strādā divos uzņēmumos ar atšķirīgu '',
LOWER(m_b.name_lv_acc),
'', tiek uzskaitīts kā divi nodarbinātie.'''
  ,'''as place of residence<br>Number of '',
LOWER(m_v_c.name_en),
'': <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b><br>Majority '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN ''in '' || m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN ''are '' || LOWER(m_v_c.name_en) || '' in '' || LOWER(m_b_c.name_en)
    ELSE ''are '' || LOWER(m_v_c.name_en) || '' in '' || m_b_c.name_en
    END,
'': <b>'',
get_pretty_number(''en'', main.value_ind),
''</b><br>Share of '',
LOWER(m_b.name_en),
'': <b>'',
ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1),
''</b>%<br><br>One inhabitant employed in two enterprises with different '',
LOWER(m_b.name_en),
'' is considered as two employees.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'panel'
  ,'''kā darba vieta<br>'',
m_v_c.name_lv_gen,
'' skaits: <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b><br>Visvairāk '',
CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN LOWER(m_b_c.name_lv_gen)
    ELSE LOWER(m_v_c.name_lv_gen) || '' '' || LOWER(m_b_c.name_lv_loc)
    END,
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>'',
m_b.name_lv_gen,
'' īpatsvars: <b>'',
REPLACE(ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1)::TEXT, ''.'', '',''),
''</b>%'''
  ,'''as place of work<br>Number of '',
LOWER(m_v_c.name_en),
'': <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b><br>Majority '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN ''in '' || m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN ''of '' || LOWER(m_v_c.name_en) || '' in '' || LOWER(m_b_c.name_en)
    ELSE ''of '' || LOWER(m_v_c.name_en) || '' in '' || m_b_c.name_en
    END,
'': <b>'',
get_pretty_number(''en'', main.value_ind),
''</b><br>Share of '',
LOWER(m_b.name_en),
'': <b>'',
ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1),
''</b>%'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'panel'
  ,'''kā dzīves vieta<br>'',
m_v_c.name_lv_gen,
'' skaits: <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b><br>'',
CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN m_b_c.name_lv
    ELSE m_b_c.name_lv_loc || '' nodarbināti''
    END,
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>'',
m_b.name_lv_gen,
'' īpatsvars: <b>'',
REPLACE(ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1)::TEXT, ''.'', '',''),
''</b>%<br><br>Viens iedzīvotājs, kas strādā divos uzņēmumos ar atšķirīgu '',
LOWER(m_b.name_lv_acc),
'', tiek uzskaitīts kā divi nodarbinātie.'''
  ,'''as place of residence<br>Number of '',
LOWER(m_v_c.name_en),
'': <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b><br>'',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN m_v_c.name_en || '' in '' || LOWER(m_b_c.name_en)
    ELSE m_v_c.name_en || '' in '' || m_b_c.name_en
    END,
'': <b>'',
get_pretty_number(''en'', main.value_ind),
''</b><br>Share of '',
LOWER(m_b.name_en),
'': <b>'',
ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1),
''</b>%<br><br>One inhabitant employed in two enterprises with different '',
LOWER(m_b.name_en),
'' is considered as two employees.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'panel'
  ,'''kā darba vieta<br>'',
m_v_c.name_lv_gen,
'' skaits: <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b><br>'',
CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN m_b_c.name_lv
    ELSE m_v_c.name_lv || '' '' || LOWER(m_b_c.name_lv_loc)
    END,
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>'',
m_b.name_lv_gen,
'' īpatsvars: <b>'',
REPLACE(ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1)::TEXT, ''.'', '',''),
''</b>%'''
  ,'''as place of work<br>Number of '',
LOWER(m_v_c.name_en),
'': <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b><br>'',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN m_v_c.name_en || '' in '' || LOWER(m_b_c.name_en)
    ELSE m_v_c.name_en || '' in '' || m_b_c.name_en
    END,
'': <b>'',
get_pretty_number(''en'', main.value_ind),
''</b><br>Share of '',
LOWER(m_b.name_en),
'': <b>'',
ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1),
''</b>%'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'panel'
  ,'''kā dzīves vieta<br>Teritorijas nodarbināto iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> €<br>Uz vienu nodarbināto: <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> €'''
  ,'''as place of residence<br>'',
m_v_c.name_en,
'' generated during the year by employed of territory: <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> €<br>Per employee: <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> €'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'panel'
  ,'''kā darba vieta<br>Teritorijas darbvietās gada laikā radītā '',
LOWER(m_v_c.name_lv),
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> €<br>Uz vienu darbvietu: <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> €'''
  ,'''as place of work<br>'',
m_v_c.name_en,
'' generated during the year in jobs of territory: <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> €<br>Per job: <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> €'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'panel'
  ,'''kā dzīves vieta<br>Vislielākā teritorijas nodarbināto iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Profesija''
    THEN LOWER(m_b_c.name_lv_dat)
  ELSE LOWER(m_b_c.name_lv_loc)
  END,
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>Uz vienu šajā '',
LOWER(m_b.name_lv_loc),
'' nodarbināto: <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> €<br>'',
m_b.name_lv_gen,
'' īpatsvars: <b>'',
REPLACE(ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1)::TEXT, ''.'', '',''),
''</b>%'''
  ,'''as place of residence<br>The highest '',
LOWER(m_v_c.name_en),
'' generated during the year by employed of territory is '',
CASE 
  WHEN m_b.name_en LIKE ''Occupation''
    THEN ''by '' || m_b_c.name_en
  WHEN m_b.name_en LIKE ''Sector''
    THEN ''in '' || LOWER(m_b_c.name_en)
  ELSE ''in '' || m_b_c.name_en
  END,
'': <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> €<br>Per employee in particular '',
LOWER(m_b.name_en),
'': <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> €<br>Share of '',
LOWER(m_b.name_en),
'': <b>'',
ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1),
''</b>%'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'panel'
  ,'''kā darba vieta<br>Vislielākā teritorijas darbvietās gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Profesija''
    THEN LOWER(m_b_c.name_lv_dat)
  ELSE LOWER(m_b_c.name_lv_loc)
  END,
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>Uz vienu '',
LOWER(m_b.name_lv_gen),
'' darbvietu: <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> €<br>'',
m_b.name_lv_gen,
'' īpatsvars: <b>'',
REPLACE(ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1)::TEXT, ''.'', '',''),
''</b>%'''
  ,'''as place of work<br>The highest '',
LOWER(m_v_c.name_en),
'' generated during the year in jobs of territory is '',
CASE 
  WHEN m_b.name_en LIKE ''Occupation''
    THEN ''by '' || m_b_c.name_en
  WHEN m_b.name_en LIKE ''Sector''
    THEN ''in '' || LOWER(m_b_c.name_en)
  ELSE ''in '' || m_b_c.name_en
  END,
'': <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> €<br>Per job of particular '',
LOWER(m_b.name_en),
'': <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> €<br>Share of '',
LOWER(m_b.name_en),
'': <b>'',
ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1),
''</b>%'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'panel'
  ,'''kā dzīves vieta<br>'',
CASE 
  WHEN m_b.name_lv LIKE ''Profesija''
    THEN ''Teritorijā dzīvojošo '' || LOWER(m_b_c.name_lv_gen) || '' gada laikā radītā '' || LOWER(m_v_c.name_lv)
  ELSE m_b_c.name_lv_loc || '' nodarbināto iedzīvotāju gada laikā radītā '' || LOWER(m_v_c.name_lv)
  END,
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>Uz vienu šajā '',
LOWER(m_b.name_lv_loc),
'' nodarbināto: <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> €<br>'',
m_b.name_lv_gen,
'' īpatsvars: <b>'',
REPLACE(ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1)::TEXT, ''.'', '',''),
''</b>%'''
  ,'''as place of residence<br>'',
m_v_c.name_en,
'' generated during the year '',
CASE 
  WHEN m_b.name_en LIKE ''Occupation''
    THEN ''by '' || m_b_c.name_en || '' living in territory''
  WHEN m_b.name_en LIKE ''Sector''
    THEN ''by employed in '' || LOWER(m_b_c.name_en)
  ELSE ''by employed in '' || m_b_c.name_en
  END,
'': <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> €<br>Per employee in particular '',
LOWER(m_b.name_en),
'': <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> €<br>Share of '',
LOWER(m_b.name_en),
'': <b>'',
ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1),
''</b>%'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'panel'
  ,'''kā darba vieta<br>Teritorijas darbvietās '',
CASE 
  WHEN m_b.name_lv LIKE ''Profesija''
    THEN LOWER(m_b_c.name_lv_gen)
  ELSE LOWER(m_b_c.name_lv_loc)
  END,
'' gada laikā radītā '',
LOWER(m_v_c.name_lv),
'': <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b><br>Uz vienu '',
LOWER(m_b.name_lv_gen),
'' darbvietu: <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> €<br>'',
m_b.name_lv_gen,
'' īpatsvars: <b>'',
REPLACE(ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1)::TEXT, ''.'', '',''),
''</b>%'''
  ,'''as place of work<br>'',
m_v_c.name_en,
'' generated during the year in jobs of territory '',
CASE 
  WHEN m_b.name_en LIKE ''Occupation''
    THEN ''by '' || m_b_c.name_en
  WHEN m_b.name_en LIKE ''Sector''
    THEN ''in '' || LOWER(m_b_c.name_en)
  ELSE ''in '' || m_b_c.name_en
  END,
'': <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> €<br>Per job in particular '',
LOWER(m_b.name_en),
'': <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> €<br>Share of '',
LOWER(m_b.name_en),
'': <b>'',
ROUND(main.value_ind / ter.value_ind::NUMERIC * 100, 1),
''</b>%'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'selected_in'
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tt_rel.value_ind),
''</b>% no visiem '',
t_h.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' strādā savas dzīvesvietas teritorijā.'''
  ,'''<b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tt_rel.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
'' work in the territory of their place of residence.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'selected_in'
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
'' strādā '',
t_w.name_lv_gen,
'' iedzīvotāji, kas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / t_ter_sel.value_ind),
''</b>% no visām '',
t_w.name_lv_gen,
'' iedzīvotāju '',
LOWER(m_v_c.name_lv_dat),
''.'''
  ,'''The resident population of '',
t_w.name_en,
'' take up <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'', which makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / t_ter_sel.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of resident population of '',
t_w.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'selected_in'
  ,
  't_h.name_lv_gen,
'' iedzīvotāji, kas strādā savas dzīvesvietas teritorijā, visbiežāk nodarbināti '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN ''nodarbināto''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātais''
  ELSE ''nodarbinātie''
  END,
''.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', ter.value_ind) LIKE ''% %''
    THEN ''nodarbināto''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātā''
  ELSE ''nodarbinātajiem''
  END,
'', kas strādā savas dzīvesvietas teritorijā.<br><br>Savas dzīvesvietas teritorijā strādā <b>'',
get_pretty_number(''lv'', 100 * ter.value_ind / ter_sel.value_ind),
''</b>% no visiem '',
t_h.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
''.'''
  ,'''Resident population of '',
t_h.name_en,
'', who work in the territory of their place of residence, are most often employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – a total of <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> employees.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b> employees who work in the territory of their place of residence.<br><br><b>'',
get_pretty_number(''en'', 100 * ter.value_ind / ter_sel.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
'' work in the territory of their place of residence.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'selected_in'
  ,
  't_h.name_lv_gen,
'' iedzīvotāji, kas strādā savas dzīvesvietas teritorijā, visbiežāk nodarbināti '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
''.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> '',
t_w.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', ter.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietas''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
'', kurās strādā vietējie iedzīvotāji.<br><br>'',
t_w.name_lv_loc,
'' atrodas <b>'',
get_pretty_number(''lv'', 100 * ter.value_ind / t_ter_sel.value_ind),
''</b>% no visām '',
t_h.name_lv_gen,
'' iedzīvotāju '',
LOWER(m_v_c.name_lv_dat),
''.'''
  ,'''Resident population of '',
t_h.name_en,
'', who work in the territory of their place of residence, are most often employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – a total of <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
''.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of '',
t_w.name_en,
'', which are taken up by local population.<br><br><b>'',
get_pretty_number(''en'', 100 * ter.value_ind / t_ter_sel.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of resident population of '',
t_w.name_en,
'' are located in '',
t_h.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'selected_in'
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> no '',
t_h.name_lv_gen,
'' iedzīvotājiem, kas strādā savas dzīvesvietas teritorijā, nodarbināti '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
''. <br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', ter.value_ind) LIKE ''% %''
    THEN ''nodarbināto''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātā''
  ELSE ''nodarbinātajiem''
  END,
'', kas strādā savas dzīvesvietas teritorijā.'''
  ,'''<b>'',
get_pretty_number(''en'', main.value_ind),
''</b> resident population of '',
t_h.name_en,
'', who work in the territory of their place of residence, are employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
''. <br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b> employees who work in the territory of their place of residence.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'selected_in'
  ,
  't_w.name_lv_loc,
'' <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_gen)
  ELSE LOWER(m_b.name_lv_gen) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
'' strādā vietējie iedzīvotāji.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> '',
t_w.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', ter.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietas''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
'', kurās strādā vietējie iedzīvotāji.'''
  ,'''In '',
t_w.name_en,
'', local resident population take up <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
''.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of '',
t_w.name_en,
'', which are taken up by local resident population.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'selected_in'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā savas dzīvesvietas teritorijā, gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'' who are employed in the territory of their place of residence, is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per employee.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'selected_in'
  ,'t_h.name_lv_loc,
'' nodarbināto vietējo iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the local resident population who are employed in '',
t_h.name_en,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per job.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'selected_in'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā savas dzīvesvietas teritorijā, vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_w.name_lv_gen,
'' iedzīvotāju, kas strādā savas dzīvesvietas teritorijā, radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The highest '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'' who are employed in the territory of their place of residence, is in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per employee.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by the resident population of '',
t_w.name_en,
'' working in the territory of their place of residence (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'selected_in'
  ,'t_w.name_lv_loc,
'' nodarbināto vietējo iedzīvotāju vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_w.name_lv_gen,
'' iedzīvotāju, kas strādā savas dzīvesvietas teritorijā, radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The highest '',
LOWER(m_v_c.name_en),
'', generated over the year by the local resident population who are employed in '',
t_w.name_en,
'', is in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per job.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by the resident population of '',
t_w.name_en,
'' working in the territory of their place of residence (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'selected_in'
  ,'t_h.name_lv_gen,
'' iedzīvotāju, kas strādā savas dzīvesvietas teritorijā, '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iedzīvotāju, kas strādā savas dzīvesvietas teritorijā, radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the local resident population of '',
t_h.name_en,
'' who are employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' in the territoy of their place of residence, is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per employee.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by the resident population of '',
t_h.name_en,
'' working in the territory of their place of residence (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'selected_in'
  ,'t_w.name_lv_loc,
'' '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' nodarbināto vietējo iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / ter.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iezīvotāju, kas strādā savas dzīvesvietas teritorijā, radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter.value_ind),
''</b> €).'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the local resident population of '',
t_w.name_en,
'' who are employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'', is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per job.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / ter.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by the resident population of '',
t_h.name_en,
'' working in the territory of their place of residence (€ <b>'',
get_pretty_number(''en'', ter.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'selected_out'
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tt_rel.value_ind),
''</b>% no visiem '',
t_h.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' (<b>'',
get_pretty_number(''lv'', tt_rel.value_ind),
''</b>) strādā ārpus dzīvesvietas teritorijas.'''
  ,'''<b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tt_rel.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
'' (<b>'',
get_pretty_number(''en'', tt_rel.value_ind),
''</b>) work outside the territory of their place of residence.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'selected_out'
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tt_rel_w.value_ind),
''</b>% no visām '',
t_w.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' (<b>'',
get_pretty_number(''lv'', tt_rel_w.value_ind),
''</b>) strādā iedzīvotāji, kas dzīvo ārpus '',
t_w.name_lv_gen,
''.'''
  ,'''<b>'',
get_pretty_number(''en'', main.value_ind),
''</b> or <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tt_rel_w.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' in '',
t_w.name_en,
'' (<b>'',
get_pretty_number(''en'', tt_rel_w.value_ind),
''</b>) are taken up by resident population living outside '',
t_w.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'selected_out'
  ,
  't_h.name_lv_gen,
'' iedzīvotāji visbiežāk strādā '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(tt_m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(tt_m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', tt_top.value_ind) LIKE ''% %''
    THEN ''nodarbināto''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', tt_top.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', tt_top.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātais''
  ELSE ''nodarbinātie''
  END,
''.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter_sel.value_ind),
''</b> '',
t_h.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', ter_sel.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter_sel.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter_sel.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātā iedzīvotāja''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
''.'''
  ,'''Resident population of '',
t_h.name_en,
'' are most often employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(tt_m_b_c.name_en)
  ELSE tt_m_b_c.name_en
  END,
'' – a total of <b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> employees.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter_sel.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'selected_out'
  ,
  't_w.name_lv_loc,
'' iedzīvotāji visbiežāk nodarbināti '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', tt_top.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', tt_top.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', tt_top.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
''.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter_sel.value_ind),
''</b> '',
t_w.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', ter_sel.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter_sel.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter_sel.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietas''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
''.'''
  ,'''Resident population in '',
t_w.name_en,
'' are most often employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' – they take up <b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
''.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter_sel.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of '',
t_w.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'selected_out'
  ,
  '''<b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> '',
t_h.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', tt_top.value_ind) LIKE ''% %''
    THEN ''iedzīvotāju''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', tt_top.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', tt_top.value_ind), 2) NOT LIKE ''11''
    THEN ''iedzīvotājs''
  ELSE ''iedzīvotāji''
  END,
'' nodarbināti '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
''.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter_sel.value_ind),
''</b> '',
t_h.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', ter_sel.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter_sel.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter_sel.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātā iedzīvotāja''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
''.'''
  ,'''<b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> '',
'' resident population of '',
t_h.name_en,
'' are employed in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
''.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter_sel.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of '',
t_h.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'selected_out'
  ,
  't_w.name_lv_loc,
'' '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(m_b_c.name_lv) || ''"''
  END,
'' ir <b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', tt_top.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', tt_top.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', tt_top.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvieta''
  ELSE LOWER(m_v_c.name_lv)
  END,
''.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', ter_sel.value_ind),
''</b> '',
t_w.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', ter_sel.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', ter_sel.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', ter_sel.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietas''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
''.'''
  ,'''There are <b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(m_b_c.name_en)
  ELSE m_b_c.name_en
  END,
'' of '',
t_w.name_en,
''.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% of <b>'',
get_pretty_number(''en'', ter_sel.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of '',
t_w.name_en,
''.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'selected_out'
  ,'t_h.name_lv_gen,
'' nodarbināto iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', tt_top.value_ind / tt_rel.value_ind),
''</b> € uz vienu nodarbināto.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the employed population of '',
t_h.name_en,
'', is € <b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', tt_top.value_ind / tt_rel.value_ind),
''</b> per employee.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'selected_out'
  ,'t_w.name_lv_gen,
'' darbvietās gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', tt_top.value_ind / tt_rel_w.value_ind),
''</b> € uz vienu darbvietu.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year in the jobs of '',
t_w.name_en,
'', is € <b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', tt_top.value_ind / tt_rel_w.value_ind),
''</b> per job.'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'selected_out'
  ,'t_h.name_lv_gen,
'' iedzīvotāju vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(tt_m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(tt_m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', tt_top.value_ind / tt_rel.value_ind),
''</b> € uz vienu nodarbināto.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iedzīvotāju radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter_sel.value_ind),
''</b> €).'''
  ,'''The highest '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'', is in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(tt_m_b_c.name_en)
  ELSE tt_m_b_c.name_en
  END,
'' – € <b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', tt_top.value_ind / tt_rel.value_ind),
''</b> per employee.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by the resident population of '',
t_h.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter_sel.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'selected_out'
  ,'t_w.name_lv_gen,
'' darbvietās vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(tt_m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(tt_m_b_c.name_lv) || ''"''
  END,
'' – <b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', tt_top.value_ind / tt_rel_w.value_ind),
''</b> € uz vienu darbvietu.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% no kopējās '',
t_w.name_lv_gen,
'' darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter_sel.value_ind),
''</b> €).'''
  ,'''The highest '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population in the jobs of '',
t_w.name_en,
'', is in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(tt_m_b_c.name_en)
  ELSE tt_m_b_c.name_en
  END,
'' – € <b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', tt_top.value_ind / tt_rel_w.value_ind),
''</b> per job.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated in jobs of '',
t_w.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter_sel.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'selected_out'
  ,'t_h.name_lv_gen,
'' iedzīvotāju '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(tt_m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(tt_m_b_c.name_lv) || ''"''
  END,
'' gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', tt_top.value_ind / tt_rel.value_ind),
''</b> € uz vienu nodarbināto.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% no kopējās '',
t_h.name_lv_gen,
'' iedzīvotāju radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter_sel.value_ind),
''</b> €).'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population of '',
t_h.name_en,
'' in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(tt_m_b_c.name_en)
  ELSE tt_m_b_c.name_en
  END,
'', is € <b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', tt_top.value_ind / tt_rel.value_ind),
''</b> per employee.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated by resident population of '',
t_h.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter_sel.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_pop (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,request_type
  ,text_display_lv
  ,text_display_en
  ,sql_string_from_join
  ,sql_string_where
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'selected_out'
  ,'t_w.name_lv_gen,
'' darbvietās '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN LOWER(tt_m_b_c.name_lv_loc)
  ELSE LOWER(m_b.name_lv_loc) || '' "'' || LOWER(tt_m_b_c.name_lv) || ''"''
  END,
'' gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', tt_top.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', tt_top.value_ind / tt_rel_w.value_ind),
''</b> € uz vienu darbvietu.<br>Tas veido <b>'',
get_pretty_number(''lv'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% no kopējās '',
t_w.name_lv_gen,
'' darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', ter_sel.value_ind),
''</b> €).'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year in jobs of '',
t_w.name_en,
'' in '',
CASE 
  WHEN m_b.name_en LIKE ''Sector''
    THEN LOWER(tt_m_b_c.name_en)
  ELSE tt_m_b_c.name_en
  END,
'', is € <b>'',
get_pretty_number(''en'', tt_top.value_ind),
''</b> or € <b>'',
get_pretty_number(''en'', tt_top.value_ind / tt_rel_w.value_ind),
''</b> per job.<br>This makes up <b>'',
get_pretty_number(''en'', 100 * tt_top.value_ind / ter_sel.value_ind),
''</b>% of the total '',
LOWER(m_v_c.name_en),
'', generated in jobs of '',
t_w.name_en,
'' (€ <b>'',
get_pretty_number(''en'', ter_sel.value_ind),
''</b>).'''
  ,NULL
  ,NULL
  );