DROP TABLE IF EXISTS tea.texts_title;

CREATE TABLE tea.texts_title (
  r_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,home_work TEXT
  ,indicator_type TEXT
  ,selected_territ TEXT
  ,indicator_selected TEXT
  ,breakdown_selected TEXT
  ,meta_title_main_lv TEXT
  ,meta_title_main_en TEXT
  ,map_title_lv TEXT
  ,map_title_en TEXT
  ,table_title_lv TEXT
  ,table_title_en TEXT
  ,legend_clusters_title_lv TEXT
  ,legend_clusters_title_en TEXT
  ,legend_sizes_title_lv TEXT
  ,legend_sizes_title_en TEXT
  ,legend_circles_title_lv TEXT
  ,legend_circles_title_en TEXT
  ,table_col_1_title_lv TEXT
  ,table_col_1_title_en TEXT
  ,table_col_2_title_lv TEXT
  ,table_col_2_title_en TEXT
  ,table_col_3_title_lv TEXT
  ,table_col_3_title_en TEXT
  ,legend_list_title_lv TEXT
  ,legend_list_title_en TEXT
  ,meta_description_main_lv TEXT
  ,meta_description_main_en TEXT
  );

ALTER TABLE tea.texts_title OWNER TO editor;

GRANT SELECT
  ON TABLE tea.texts_title
  TO vdvv_web
    ,editor_texts
    ,admin_texts;

GRANT UPDATE
  ON TABLE tea.texts_title
  TO editor_texts
    ,admin_texts;

GRANT DELETE
  ,INSERT
  ON TABLE tea.texts_title
  TO admin_texts;

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'empl'
  ,'all'
  ,'none'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'''Teritorijas '',
LOWER(m_v_c.name_lv_gen),
'' skaits un nodarbinātības līmenis'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' and employment rate in territory'''
  ,'''Teritorijas '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' of territory'''
  ,'''Nodarbinātības līmenis ('',
LOWER(m_v_c.name_lv_gen),
'' skaits pret iedzīvotājiem 15–64 gadu vecumā), %'''
  ,'''Employment rate (number of '',
LOWER(m_v_c.name_en),
'' per population aged 15–64), %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātības līmenis, %'''
  ,'''Employment rate, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'empl'
  ,'all'
  ,'none'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'m_v_c.name_lv_gen,
'' skaits teritorijā un uz 100 iedzīvotājiem 15–64 gadu vecumā'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' in territory and per 100 inhabitants aged 15–64'''
  ,'m_v_c.name_lv_gen,
'' skaits teritorijā'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' in territory'''
  ,'m_v_c.name_lv_gen,
'' skaits uz 100 iedzīvotājiem 15–64 gadu vecumā'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' per 100 inhabitants aged 15–64'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'m_v_c.name_lv,
'' uz 100 darbspējas vecuma iedzīvotājiem'''
  ,'m_v_c.name_en,
'' per 100 inhabitants of working age'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'empl'
  ,'all'
  ,'selected'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'''Teritorijas '',
LOWER(m_v_c.name_lv_gen),
'' '',
CASE 
    WHEN m_b.name_lv LIKE ''Sektors''
      THEN ''izplatītākais ''
    ELSE ''izplatītākā ''
    END,
LOWER(m_b.name_lv),
'' pēc nodarbināto skaita un īpatsvara'''
  ,'''Top '',
LOWER(m_b.name_en),
'' of '',
LOWER(m_v_c.name_en),
'' of territory by number and share of employed'''
  ,'''Teritorijas '',
LOWER(m_v_c.name_lv),
'' pēc '',
LOWER(m_b.name_lv_gen)'
  ,'m_v_c.name_en,
'' of territory by '',
LOWER(m_b.name_en)'
  ,'m_v_c.name_lv_gen,
'' īpatsvars izplatītākajā '',
LOWER(m_b.name_lv_loc),
'', %'''
  ,'''Share of '',
LOWER(m_v_c.name_en),
'' in top '',
LOWER(m_b.name_en),
'', %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Īpatsvars, %'''
  ,'''Share, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'empl'
  ,'all'
  ,'selected'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'''Teritorijas '',
CASE 
    WHEN m_b.name_lv LIKE ''Sektors''
      THEN ''izplatītākais ''
    ELSE ''izplatītākā ''
    END,
LOWER(m_b.name_lv),
'' pēc '',
LOWER(m_v_c.name_lv_gen),
'' skaita un īpatsvara'''
  ,'''Top '',
LOWER(m_b.name_en),
'' of territory by number and share of jobs'''
  ,'''Teritorijas '',
LOWER(m_v_c.name_lv),
'' pēc '',
LOWER(m_b.name_lv_gen)'
  ,'m_v_c.name_en,
'' of territory by '',
LOWER(m_b.name_en)'
  ,'m_v_c.name_lv_gen,
'' īpatsvars izplatītākajā '',
LOWER(m_b.name_lv_loc),
'', %'''
  ,'''Share of '',
LOWER(m_v_c.name_en),
'' in top '',
LOWER(m_b.name_en),
'', %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Īpatsvars, %'''
  ,'''Share, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'empl'
  ,'all'
  ,'selected'
  ,'selected'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN ''Teritorijā dzīvojošo '' || LOWER(m_b_c.name_lv_gen)
    ELSE m_b_c.name_lv_loc || '' '' || LOWER(m_v_c.name_lv_gen)
    END,
'' skaits un īpatsvars'''
  ,'''Number and share of '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN m_b_c.name_en || '' living in the territory''
    WHEN m_b.name_en LIKE ''Sector''
      THEN LOWER(m_v_c.name_en) || '' in '' || LOWER(m_b_c.name_en)
    ELSE LOWER(m_v_c.name_en) || '' in '' || m_b_c.name_en
    END'
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN ''Teritorijā dzīvojošie '' || LOWER(m_b_c.name_lv)
    ELSE m_b_c.name_lv_loc || '' '' || LOWER(m_v_c.name_lv)
    END'
  ,'CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN m_b_c.name_en || '' living in the territory''
    WHEN m_b.name_en LIKE ''Sector''
      THEN m_v_c.name_en || '' in '' || LOWER(m_b_c.name_en)
    ELSE m_v_c.name_en || '' in '' || m_b_c.name_en
    END'
  ,'m_b.name_lv_loc,
'' '',
LOWER(m_v_c.name_lv_gen),
'' īpatsvars, %'''
  ,'''Share of '',
LOWER(m_v_c.name_en),
'' in '',
LOWER(m_b.name_en),
'', %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Īpatsvars, %'''
  ,'''Share, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'empl'
  ,'all'
  ,'selected'
  ,'selected'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN m_b_c.name_lv_gen || '' '' || LOWER(m_v_c.name_lv_gen) || '' skaits un īpatsvars''
    ELSE m_v_c.name_lv_gen || '' skaits un īpatsvars '' || LOWER(m_b_c.name_lv_loc)
    END'
  ,'''Number and share of '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN LOWER(m_v_c.name_en) || '' of '' || m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN LOWER(m_v_c.name_en) || '' in '' || LOWER(m_b_c.name_en)
    ELSE LOWER(m_v_c.name_en) || '' in '' || m_b_c.name_en
    END'
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN m_b_c.name_lv_gen || '' '' || LOWER(m_v_c.name_lv)
    ELSE m_v_c.name_lv || '' '' || LOWER(m_b_c.name_lv_loc)
    END'
  ,'CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN m_v_c.name_en || '' of '' || m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN m_v_c.name_en || '' in '' || LOWER(m_b_c.name_en)
    ELSE m_v_c.name_en || '' in '' || m_b_c.name_en
    END'
  ,'m_v_c.name_lv_gen,
'' īpatsvars '',
LOWER(m_b.name_lv_loc),
'', %'''
  ,'''Share of '',
LOWER(m_v_c.name_en),
'' in '',
LOWER(m_b.name_en),
'', %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Īpatsvars, %'''
  ,'''Share, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv),
'' pēc darba atrašanās vietas, to skaits un īpatsvars'''
  ,'''Number and share of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en,
'' by location of place of work'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv),
'' pēc darba atrašanās vietas'''
  ,'m_v_c.name_en,
'' of '',
t.name_en,
'' by workplace location'''
  ,'''Īpatsvars kopējā '',
t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaitā, %'''
  ,'''Share in total number of '',
LOWER(m_v_c.name_en),
'' in '',
t.name_en,
'', %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Darba atrašanās vieta'''
  ,'''Workplace location'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en'
  ,'''Īpatsvars, %'''
  ,'''Share, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'none'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv),
'' pēc nodarbinātā dzīvesvietas, to skaits un īpatsvars'''
  ,'''Number and share of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en,
'' by place of residence of employed'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv),
'' pēc nodarbinātā dzīvesvietas'''
  ,'m_v_c.name_en,
'' of '',
t.name_en,
'' by place of residence of employed'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' īpatsvars dzīvesvietas teritorijā, %'''
  ,'''Share of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en,
'' in territory of place of residence, %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Nodarbinātā dzīvesvieta'''
  ,'''Residence location'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en'
  ,'''Īpatsvars dzīvesvietas teritorijā, %'''
  ,'''Share in territory of place of residence, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' '',
CASE 
    WHEN m_b.name_lv LIKE ''Sektors''
      THEN ''izplatītākais ''
    ELSE ''izplatītākā ''
    END,
LOWER(m_b.name_lv),
'' pēc darba atrašanās vietas'''
  ,'''Top '',
LOWER(m_b.name_en),
'' of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en,
'' by location of place of work'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv),
'' pēc '',
LOWER(m_b.name_lv_gen),
'' un darba atrašanās vietas'''
  ,'m_v_c.name_en,
'' of '',
t.name_en,
'' by '',
LOWER(m_b.name_en),
'' and workplace location'''
  ,'''Īpatsvars kopējā '',
t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaitā, %'''
  ,'''Share in total number of '',
LOWER(m_v_c.name_en),
'' in '',
t.name_en,
'', %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Darba atrašanās vieta'''
  ,'''Workplace location'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en'
  ,'''Īpatsvars, %'''
  ,'''Share, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'t.name_lv_gen,
CASE 
    WHEN m_b.name_lv LIKE ''Sektors''
      THEN '' izplatītākais ''
    ELSE '' izplatītākā ''
    END,
LOWER(m_b.name_lv),
'' pēc '',
LOWER(m_v_c.name_lv_gen),
'' skaita un nodarbinātā dzīvesvietas'''
  ,'''Top '',
LOWER(m_b.name_en),
'' of '',
t.name_en,
'' by number of '',
LOWER(m_v_c.name_en),
'' and place of residence of employee'''
  ,'t.name_lv_gen,
'' darbvietas pēc '',
LOWER(m_b.name_lv_gen),
'' un nodarbinātā dzīvesvietas'''
  ,'m_v_c.name_en,
'' of '',
t.name_en,
'' by '',
LOWER(m_b.name_en),
'' and place of residence of employed'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' īpatsvars dzīvesvietas teritorijā, %'''
  ,'''Share of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en,
'' in territory of place of residence, %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Nodarbinātā dzīvesvieta'''
  ,'''Residence location'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en'
  ,'''Īpatsvars, %'''
  ,'''Share, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN t.name_lv_loc || '' dzīvojošo '' || LOWER(m_b_c.name_lv_gen) || '' skaits un īpatsvars''
    ELSE t.name_lv_gen || '' '' || LOWER(m_v_c.name_lv_gen) || '' skaits un īpatsvars '' || LOWER(m_b_c.name_lv_loc)
    END,
'' pēc darba atrašanās vietas'''
  ,'''Number and share of '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN m_b_c.name_en || '' living in '' || t.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN LOWER(m_v_c.name_en) || '' of '' || t.name_en || '' in '' || LOWER(m_b_c.name_en)
    ELSE LOWER(m_v_c.name_en) || '' of '' || t.name_en || '' in '' || m_b_c.name_en
    END,
'' by location of place of work'''
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN t.name_lv_loc || '' dzīvojošie '' || LOWER(m_b_c.name_lv)
    ELSE t.name_lv_gen || '' '' || LOWER(m_v_c.name_lv) || '' '' || LOWER(m_b_c.name_lv_loc)
    END,
'' pēc darba atrašanās vietas'''
  ,'CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN m_b_c.name_en || '' living in '' || t.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN m_v_c.name_en || '' of '' || t.name_en || '' in '' || LOWER(m_b_c.name_en)
    ELSE m_v_c.name_en || '' of '' || t.name_en || '' in '' || m_b_c.name_en
    END,
'' by workplace location'''
  ,'m_b.name_lv_loc,
'' '',
LOWER(m_v_c.name_lv_gen),
'' īpatsvars, %'''
  ,'''Share of '',
LOWER(m_v_c.name_en),
'' in '',
LOWER(m_b.name_en),
'', %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Darba atrašanās vieta'''
  ,'''Workplace location'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en'
  ,'''Īpatsvars, %'''
  ,'''Share, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'t.name_lv_gen,
'' '',
LOWER(m_b_c.name_lv_gen),
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaits un īpatsvars pēc nodarbinātā dzīvesvietas'''
  ,'''Number and share of '',
LOWER(m_v_c.name_en),
'' of '',
CASE 
    WHEN m_b.name_en LIKE ''Sector''
      THEN LOWER(m_b_c.name_en)
    ELSE m_b_c.name_en
    END,
'' of '',
t.name_en,
'' by place of residence of employee'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_b_c.name_lv_gen),
'' darbvietas pēc nodarbinātā dzīvesvietas'''
  ,'m_v_c.name_en,
'' of '',
CASE 
    WHEN m_b.name_en LIKE ''Sector''
      THEN LOWER(m_b_c.name_en)
    ELSE m_b_c.name_en
    END,
'' of '',
t.name_en,
'' by place of residence of employed'''
  ,'m_v_c.name_lv_gen,
'' īpatsvars '',
LOWER(m_b.name_lv_loc),
'', %'''
  ,'''Share of '',
LOWER(m_v_c.name_en),
'' in '',
LOWER(m_b.name_en),
'', %'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Nodarbinātā dzīvesvieta'''
  ,'''Residence location'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en'
  ,'''Īpatsvars, %'''
  ,'''Share, %'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'other'
  ,'all'
  ,'none'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'''Teritorijas nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv),
'' un tās apmērs uz vienu nodarbināto'''
  ,'m_v_c.name_en,
'' generated by employed residents of territory and amount of it per employee'''
  ,'''Teritorijas nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by employed residents of territory'''
  ,'m_v_c.name_lv,
'' uz vienu nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed, €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv,
'', tūkst. €'''
  ,'m_v_c.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'other'
  ,'all'
  ,'none'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'''Teritorijā radītā '',
LOWER(m_v_c.name_lv),
'' un tās apmērs uz vienu darbvietu'''
  ,'m_v_c.name_en,
'' in territory and amount of it per job'''
  ,'''Teritorijas darbvietās radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated in jobs of territory'''
  ,'m_v_c.name_lv,
'' uz vienu darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job, €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv,
'', tūkst. €'''
  ,'m_v_c.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'other'
  ,'all'
  ,'selected'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'m_b.name_lv,
'' ar vislielāko '',
LOWER(m_v_c.name_lv_acc),
'' teritorijas nodarbināto iedzīvotāju darbvietā un tās apmērs uz vienu nodarbināto'''
  ,'''Top '',
LOWER(m_b.name_en),
'' in jobs engaging employed residents of territory by '',
LOWER(m_v_c.name_en),
'' and amount of it per one employed'''
  ,'''Teritorijas nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv),
'' pēc '',
LOWER(m_b.name_lv_gen)'
  ,'m_v_c.name_en,
'' generated by employed residents of territory by '',
LOWER(m_b.name_en)'
  ,'m_v_c.name_lv,
'' uz vienu izplatītākajā '',
LOWER(m_b.name_lv_loc),
'' nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed in top '',
LOWER(m_b.name_en),
'', €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv,
'', tūkst. €'''
  ,'m_v_c.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'other'
  ,'all'
  ,'selected'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'m_b.name_lv,
'' ar vislielāko '',
LOWER(m_v_c.name_lv_acc),
'' teritorijā un tās apmērs uz vienu darbvietu'''
  ,'''Top '',
LOWER(m_b.name_en),
'' of territory by '',
LOWER(m_v_c.name_en),
'' and amount of it per job'''
  ,'''Teritorijas darbvietās radītā '',
LOWER(m_v_c.name_lv),
'' pēc '',
LOWER(m_b.name_lv_gen)'
  ,'m_v_c.name_en,
'' generated in jobs of territory by '',
LOWER(m_b.name_en)'
  ,'m_v_c.name_lv,
'' uz vienu '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN ''izplatītākā ''
  ELSE ''izplatītākās ''
  END,
LOWER(m_b.name_lv_gen),
'' darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job in top '',
LOWER(m_b.name_en),
'', €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv,
'', tūkst. €'''
  ,'m_v_c.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'other'
  ,'all'
  ,'selected'
  ,'selected'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN ''Teritorijā dzīvojošo '' || LOWER(m_b_c.name_lv_gen)
    ELSE m_b_c.name_lv_loc || '' nodarbināto iedzīvotāju''
    END,
'' radītā '',
LOWER(m_v_c.name_lv),
'' un tās apmērs uz vienu nodarbināto'''
  ,'m_v_c.name_en,
'' generated by '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN m_b_c.name_en || '' living in territory''
    WHEN m_b.name_en LIKE ''Sector''
      THEN ''employed in '' || LOWER(m_b_c.name_en)
    ELSE ''employed in '' || m_b_c.name_en
    END,
'' and amount of it per one employed'''
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN ''Teritorijā dzīvojošo '' || LOWER(m_b_c.name_lv_gen)
    ELSE m_b_c.name_lv_loc || '' nodarbināto iedzīvotāju''
    END,
'' radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN m_b_c.name_en || '' living in territory''
    WHEN m_b.name_en LIKE ''Sector''
      THEN ''employed in '' || LOWER(m_b_c.name_en)
    ELSE ''employed in '' || m_b_c.name_en
    END'
  ,'m_v_c.name_lv,
'' uz vienu '',
LOWER(m_b.name_lv_loc),
'' nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed in '',
LOWER(m_b.name_en),
'', €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv,
'', tūkst. €'''
  ,'m_v_c.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'other'
  ,'all'
  ,'selected'
  ,'selected'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN m_b_c.name_lv_gen
    ELSE m_b_c.name_lv_loc
    END,
'' radītā '',
LOWER(m_v_c.name_lv),
'' un tās apmērs uz vienu darbvietu'''
  ,'m_v_c.name_en,
'' generated '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN ''by '' || m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN '' in '' || LOWER(m_b_c.name_en)
    ELSE '' in '' || m_b_c.name_en
    END,
'' and amount of it per one job'''
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN m_b_c.name_lv_gen
    ELSE m_b_c.name_lv_loc
    END,
'' radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN ''by '' || m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN '' in '' || LOWER(m_b_c.name_en)
    ELSE '' in '' || m_b_c.name_en
    END'
  ,'m_v_c.name_lv,
'' uz vienu '',
LOWER(m_b.name_lv_gen),
'' darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job in '',
LOWER(m_b.name_en),
'', €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Teritorija'''
  ,'''Territory'''
  ,'m_v_c.name_lv,
'', tūkst. €'''
  ,'m_v_c.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'t.name_lv_gen,
'' nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv),
'' pēc darba atrašanās vietas, tās apmērs uz vienu nodarbināto'''
  ,'m_v_c.name_en,
'' generated by employed of '',
t.name_en,
'' by workplace location, amount of it per one employed'''
  ,'t.name_lv_gen,
'' nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv),
'' pēc darba atrašanās vietas'''
  ,'m_v_c.name_en,
'' generated by employed residents of '',
t.name_en,
'' by workplace location'''
  ,'m_v_c.name_lv,
'' uz vienu nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed, €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Darba atrašanās vieta'''
  ,'''Workplace location'''
  ,'t.name_lv_gen,
'' iedzīvotāju radītā '',
LOWER(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'' generated by inhabitants of '',
t.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'none'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'t.name_lv_gen,
'' darbvietās radītā '',
LOWER(m_v_c.name_lv),
'' pēc nodarbinātā dzīvesvietas, tās apmērs uz vienu darbvietu'''
  ,'m_v_c.name_en,
'' generated in jobs of '',
t.name_en,
'' by place of residence of employed, amount of it per one job'''
  ,'t.name_lv_gen,
'' darbvietās radītā '',
LOWER(m_v_c.name_lv),
'' pēc nodarbinātā dzīvesvietas'''
  ,'m_v_c.name_en,
'' generated in jobs of '',
t.name_en,
'' by place of residence of employed'''
  ,'m_v_c.name_lv,
'' uz vienu darbavietu, €'''
  ,'m_v_c.name_en,
'' per one job, €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Nodarbinātā dzīvesvieta'''
  ,'''Residence location'''
  ,'t.name_lv_gen,
'' darbvietās radītā '',
lower(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'' generated in jobs in '',
t.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'m_b.name_lv,
'' ar vislielāko '',
t.name_lv_gen,
'' nodarbināto iedzīvotāju radīto '',
LOWER(m_v_c.name_lv_acc),
'' pēc darba atrašanās vietas'''
  ,'''Top '',
LOWER(m_b.name_en),
'' of employed of '',
t.name_en,
'' by '',
LOWER(m_v_c.name_en),
'' and workplace location'''
  ,'t.name_lv_gen,
'' nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv),
'' pēc '',
LOWER(m_b.name_lv_gen),
'' un darba atrašanās vietas'''
  ,'m_v_c.name_en,
'' generated by employed residents of '',
t.name_en,
'' by '',
LOWER(m_b.name_en),
'' and workplace location'''
  ,'m_v_c.name_lv,
'' uz vienu izplatītākajā '',
LOWER(m_b.name_lv_loc),
'' nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed in top '',
LOWER(m_b.name_en),
'', €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Darba atrašanās vieta'''
  ,'''Workplace location'''
  ,'t.name_lv_gen,
'' iedzīvotāju radītā '',
LOWER(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'' generated by inhabitants of '',
t.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'none'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'m_b.name_lv,
'' ar vislielāko '',
LOWER(m_v_c.name_lv_acc),
'' '',
t.name_lv_gen,
'' darbvietās pēc nodarbinātā dzīvesvietas'''
  ,'''Top '',
LOWER(m_b.name_en),
'' of jobs of '',
t.name_en,
'' by '',
LOWER(m_v_c.name_en),
'' and place of residence of employed'''
  ,'t.name_lv_gen,
'' darbvietās radītā '',
LOWER(m_v_c.name_lv),
'' pēc '',
LOWER(m_b.name_lv_gen),
'' un nodarbinātā dzīvesvietas'''
  ,'m_v_c.name_en,
'' generated in jobs of '',
t.name_en,
'' by '',
LOWER(m_b.name_en),
'' and place of residence of employed'''
  ,'m_v_c.name_lv,
'' uz vienu '',
CASE 
  WHEN m_b.name_lv LIKE ''Sektors''
    THEN ''izplatītākā ''
  ELSE ''izplatītākās ''
  END,
LOWER(m_b.name_lv_gen),
'' darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job in top '',
LOWER(m_b.name_en),
'', €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Nodarbinātā dzīvesvieta'''
  ,'''Residence location'''
  ,'t.name_lv_gen,
'' darbvietās radītā '',
lower(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'' generated in jobs in '',
t.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN t.name_lv_loc || '' dzīvojošo '' || LOWER(m_b_c.name_lv_gen)
    ELSE t.name_lv_gen || '' nodarbināto iedzīvotāju '' || LOWER(m_b_c.name_lv_loc)
    END,
'' radītā '',
LOWER(m_v_c.name_lv),
'' pēc darba atrašanās vietas'''
  ,'m_v_c.name_en,
'' generated '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN ''by '' || m_b_c.name_en || '' living in ''
    WHEN m_b.name_en LIKE ''Sector''
      THEN ''in '' || LOWER(m_b_c.name_en) || '' by employed of ''
    ELSE ''in '' || m_b_c.name_en || '' by employed of ''
    END,
t.name_en,
'' by workplace location'''
  ,'CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN t.name_lv_loc || '' dzīvojošo '' || LOWER(m_b_c.name_lv_gen)
    ELSE t.name_lv_gen || '' nodarbināto iedzīvotāju '' || LOWER(m_b_c.name_lv_loc)
    END,
'' radītā '',
LOWER(m_v_c.name_lv),
'' pēc darba atrašanās vietas'''
  ,'m_v_c.name_en,
'' generated '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN ''by '' || m_b_c.name_en || '' living in ''
    WHEN m_b.name_en LIKE ''Sector''
      THEN ''in '' || LOWER(m_b_c.name_en) || '' by employed of ''
    ELSE ''in '' || m_b_c.name_en || '' by employed of ''
    END,
t.name_en,
'' by workplace location'''
  ,'m_v_c.name_lv,
'' uz vienu '',
LOWER(m_b.name_lv_loc),
'' nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed in '',
LOWER(m_b.name_en),
'', €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Darba atrašanās vieta'''
  ,'''Workplace location'''
  ,'t.name_lv_gen,
'' iedzīvotāju radītā '',
LOWER(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'' generated by inhabitants of '',
t.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title (
  home_work
  ,indicator_type
  ,selected_territ
  ,indicator_selected
  ,breakdown_selected
  ,meta_title_main_lv
  ,meta_title_main_en
  ,map_title_lv
  ,map_title_en
  ,table_title_lv
  ,table_title_en
  ,legend_clusters_title_lv
  ,legend_clusters_title_en
  ,legend_sizes_title_lv
  ,legend_sizes_title_en
  ,legend_circles_title_lv
  ,legend_circles_title_en
  ,table_col_1_title_lv
  ,table_col_1_title_en
  ,table_col_2_title_lv
  ,table_col_2_title_en
  ,table_col_3_title_lv
  ,table_col_3_title_en
  ,legend_list_title_lv
  ,legend_list_title_en
  ,meta_description_main_lv
  ,meta_description_main_en
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'selected'
  ,'selected'
  ,'m_v_c.name_lv,
COALESCE('' - '' || m_b.name_lv, ''''),
COALESCE('' - '' || t.name_lv, '''')'
  ,'m_v_c.name_en,
COALESCE('' - '' || m_b.name_en, ''''),
COALESCE('' - '' || t.name_en, '''')'
  ,'t.name_lv_loc,
'' '',
CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN LOWER(m_b_c.name_lv_gen)
    ELSE LOWER(m_b_c.name_lv_loc)
    END,
'' radītā '',
LOWER(m_v_c.name_lv),
'' pēc nodarbinātā dzīvesvietas'''
  ,'m_v_c.name_en,
'' generated '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN ''by '' || m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN ''in '' || LOWER(m_b_c.name_en)
    ELSE ''in '' || m_b_c.name_en
    END,
'' in '',
t.name_en,
'' by place of residence of employed'''
  ,'t.name_lv_loc,
'' '',
CASE 
    WHEN m_b.name_lv LIKE ''Profesija''
      THEN LOWER(m_b_c.name_lv_gen)
    ELSE LOWER(m_b_c.name_lv_loc)
    END,
'' radītā '',
LOWER(m_v_c.name_lv),
'' pēc nodarbinātā dzīvesvietas'''
  ,'m_v_c.name_en,
'' generated '',
CASE 
    WHEN m_b.name_en LIKE ''Occupation''
      THEN ''by '' || m_b_c.name_en
    WHEN m_b.name_en LIKE ''Sector''
      THEN ''in '' || LOWER(m_b_c.name_en)
    ELSE ''in '' || m_b_c.name_en
    END,
'' in '',
t.name_en,
'' by place of residence of employed'''
  ,'m_v_c.name_lv,
'' uz vienu '',
LOWER(m_b.name_lv_gen),
'' darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job in '',
LOWER(m_b.name_en),
'', €'''
  ,'m_v_c.name_lv,
'', €'''
  ,'m_v_c.name_en,
'', €'''
  ,'''Nodarbinātā'''
  ,'''Employed individual''''s'''
  ,'''Nodarbinātā dzīvesvieta'''
  ,'''Residence location'''
  ,'t.name_lv_gen,
'' darbvietās radītā '',
LOWER(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'' generated in jobs in '',
t.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz vienu darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job, €'''
  ,'m_b.name_lv'
  ,'m_b.name_en'
  ,NULL
  ,NULL
  );